//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/artur/RiderProjects/Markdown-to-LaTeX/Markdown-to-LaTeX/Markdown.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace MarkdownParsing {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IMarkdownListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class MarkdownBaseListener : IMarkdownListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.document"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDocument([NotNull] Markdown.DocumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.document"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDocument([NotNull] Markdown.DocumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>atxHeading</c>
	/// labeled alternative in <see cref="Markdown.heading"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtxHeading([NotNull] Markdown.AtxHeadingContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>atxHeading</c>
	/// labeled alternative in <see cref="Markdown.heading"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtxHeading([NotNull] Markdown.AtxHeadingContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>setextHeading</c>
	/// labeled alternative in <see cref="Markdown.heading"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSetextHeading([NotNull] Markdown.SetextHeadingContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>setextHeading</c>
	/// labeled alternative in <see cref="Markdown.heading"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSetextHeading([NotNull] Markdown.SetextHeadingContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>emptyHeading</c>
	/// labeled alternative in <see cref="Markdown.heading"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEmptyHeading([NotNull] Markdown.EmptyHeadingContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>emptyHeading</c>
	/// labeled alternative in <see cref="Markdown.heading"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEmptyHeading([NotNull] Markdown.EmptyHeadingContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.headingStart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHeadingStart([NotNull] Markdown.HeadingStartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.headingStart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHeadingStart([NotNull] Markdown.HeadingStartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.setextEnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSetextEnd([NotNull] Markdown.SetextEndContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.setextEnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSetextEnd([NotNull] Markdown.SetextEndContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.horizontalLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHorizontalLine([NotNull] Markdown.HorizontalLineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.horizontalLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHorizontalLine([NotNull] Markdown.HorizontalLineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.hLineDBegin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHLineDBegin([NotNull] Markdown.HLineDBeginContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.hLineDBegin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHLineDBegin([NotNull] Markdown.HLineDBeginContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.hLineUBegin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHLineUBegin([NotNull] Markdown.HLineUBeginContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.hLineUBegin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHLineUBegin([NotNull] Markdown.HLineUBeginContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.hLineSBegin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHLineSBegin([NotNull] Markdown.HLineSBeginContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.hLineSBegin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHLineSBegin([NotNull] Markdown.HLineSBeginContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.indent3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndent3([NotNull] Markdown.Indent3Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.indent3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndent3([NotNull] Markdown.Indent3Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.indent2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndent2([NotNull] Markdown.Indent2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.indent2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndent2([NotNull] Markdown.Indent2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.indent1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndent1([NotNull] Markdown.Indent1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.indent1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndent1([NotNull] Markdown.Indent1Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.fencedCode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFencedCode([NotNull] Markdown.FencedCodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.fencedCode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFencedCode([NotNull] Markdown.FencedCodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.indentedCodeBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndentedCodeBlock([NotNull] Markdown.IndentedCodeBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.indentedCodeBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndentedCodeBlock([NotNull] Markdown.IndentedCodeBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.indentedCode1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndentedCode1([NotNull] Markdown.IndentedCode1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.indentedCode1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndentedCode1([NotNull] Markdown.IndentedCode1Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterList([NotNull] Markdown.ListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitList([NotNull] Markdown.ListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.list1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterList1([NotNull] Markdown.List1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.list1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitList1([NotNull] Markdown.List1Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.list2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterList2([NotNull] Markdown.List2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.list2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitList2([NotNull] Markdown.List2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.list3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterList3([NotNull] Markdown.List3Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.list3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitList3([NotNull] Markdown.List3Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.iList3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIList3([NotNull] Markdown.IList3Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.iList3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIList3([NotNull] Markdown.IList3Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.iList2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIList2([NotNull] Markdown.IList2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.iList2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIList2([NotNull] Markdown.IList2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.iList1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIList1([NotNull] Markdown.IList1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.iList1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIList1([NotNull] Markdown.IList1Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.iList0"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIList0([NotNull] Markdown.IList0Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.iList0"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIList0([NotNull] Markdown.IList0Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.iListItem3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIListItem3([NotNull] Markdown.IListItem3Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.iListItem3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIListItem3([NotNull] Markdown.IListItem3Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.iListItem2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIListItem2([NotNull] Markdown.IListItem2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.iListItem2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIListItem2([NotNull] Markdown.IListItem2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.iListItem1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIListItem1([NotNull] Markdown.IListItem1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.iListItem1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIListItem1([NotNull] Markdown.IListItem1Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.iListItem0"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIListItem0([NotNull] Markdown.IListItem0Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.iListItem0"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIListItem0([NotNull] Markdown.IListItem0Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.iListBegin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIListBegin([NotNull] Markdown.IListBeginContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.iListBegin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIListBegin([NotNull] Markdown.IListBeginContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.eList3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEList3([NotNull] Markdown.EList3Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.eList3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEList3([NotNull] Markdown.EList3Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.eList2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEList2([NotNull] Markdown.EList2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.eList2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEList2([NotNull] Markdown.EList2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.eList1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEList1([NotNull] Markdown.EList1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.eList1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEList1([NotNull] Markdown.EList1Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.eList0"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEList0([NotNull] Markdown.EList0Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.eList0"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEList0([NotNull] Markdown.EList0Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.eListItem3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEListItem3([NotNull] Markdown.EListItem3Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.eListItem3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEListItem3([NotNull] Markdown.EListItem3Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.eListItem2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEListItem2([NotNull] Markdown.EListItem2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.eListItem2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEListItem2([NotNull] Markdown.EListItem2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.eListItem1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEListItem1([NotNull] Markdown.EListItem1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.eListItem1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEListItem1([NotNull] Markdown.EListItem1Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.eListItem0"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEListItem0([NotNull] Markdown.EListItem0Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.eListItem0"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEListItem0([NotNull] Markdown.EListItem0Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.eListBegin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEListBegin([NotNull] Markdown.EListBeginContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.eListBegin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEListBegin([NotNull] Markdown.EListBeginContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.blockQuote"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlockQuote([NotNull] Markdown.BlockQuoteContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.blockQuote"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlockQuote([NotNull] Markdown.BlockQuoteContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.blockQuoteLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlockQuoteLine([NotNull] Markdown.BlockQuoteLineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.blockQuoteLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlockQuoteLine([NotNull] Markdown.BlockQuoteLineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.emptyBlockQuoteLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEmptyBlockQuoteLine([NotNull] Markdown.EmptyBlockQuoteLineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.emptyBlockQuoteLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEmptyBlockQuoteLine([NotNull] Markdown.EmptyBlockQuoteLineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.blockQuoteStart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlockQuoteStart([NotNull] Markdown.BlockQuoteStartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.blockQuoteStart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlockQuoteStart([NotNull] Markdown.BlockQuoteStartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTable([NotNull] Markdown.TableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTable([NotNull] Markdown.TableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.headerRow"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHeaderRow([NotNull] Markdown.HeaderRowContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.headerRow"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHeaderRow([NotNull] Markdown.HeaderRowContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.contentRow"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContentRow([NotNull] Markdown.ContentRowContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.contentRow"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContentRow([NotNull] Markdown.ContentRowContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.cellContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCellContent([NotNull] Markdown.CellContentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.cellContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCellContent([NotNull] Markdown.CellContentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.separatorRow"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSeparatorRow([NotNull] Markdown.SeparatorRowContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.separatorRow"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSeparatorRow([NotNull] Markdown.SeparatorRowContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.separatorContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSeparatorContent([NotNull] Markdown.SeparatorContentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.separatorContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSeparatorContent([NotNull] Markdown.SeparatorContentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.imageLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImageLine([NotNull] Markdown.ImageLineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.imageLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImageLine([NotNull] Markdown.ImageLineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.linkLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLinkLine([NotNull] Markdown.LinkLineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.linkLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLinkLine([NotNull] Markdown.LinkLineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.textLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTextLine([NotNull] Markdown.TextLineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.textLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTextLine([NotNull] Markdown.TextLineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.requiredText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRequiredText([NotNull] Markdown.RequiredTextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.requiredText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRequiredText([NotNull] Markdown.RequiredTextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.optionalText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOptionalText([NotNull] Markdown.OptionalTextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.optionalText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOptionalText([NotNull] Markdown.OptionalTextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.displayText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDisplayText([NotNull] Markdown.DisplayTextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.displayText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDisplayText([NotNull] Markdown.DisplayTextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.linkText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLinkText([NotNull] Markdown.LinkTextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.linkText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLinkText([NotNull] Markdown.LinkTextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.urlText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUrlText([NotNull] Markdown.UrlTextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.urlText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUrlText([NotNull] Markdown.UrlTextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.headingText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHeadingText([NotNull] Markdown.HeadingTextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.headingText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHeadingText([NotNull] Markdown.HeadingTextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.fencedText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFencedText([NotNull] Markdown.FencedTextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.fencedText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFencedText([NotNull] Markdown.FencedTextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.codeText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCodeText([NotNull] Markdown.CodeTextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.codeText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCodeText([NotNull] Markdown.CodeTextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.link"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLink([NotNull] Markdown.LinkContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.link"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLink([NotNull] Markdown.LinkContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.urlLink"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUrlLink([NotNull] Markdown.UrlLinkContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.urlLink"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUrlLink([NotNull] Markdown.UrlLinkContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Markdown.textLink"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTextLink([NotNull] Markdown.TextLinkContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Markdown.textLink"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTextLink([NotNull] Markdown.TextLinkContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace MarkdownParsing
