//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/artur/RiderProjects/Markdown-to-LaTeX/Markdown-to-LaTeX/MarkdownParser.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace MarkdownParsing {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="MarkdownParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IMarkdownParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.document"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDocument([NotNull] MarkdownParser.DocumentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.document"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDocument([NotNull] MarkdownParser.DocumentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.heading"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHeading([NotNull] MarkdownParser.HeadingContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.heading"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHeading([NotNull] MarkdownParser.HeadingContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.emptyHeading"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmptyHeading([NotNull] MarkdownParser.EmptyHeadingContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.emptyHeading"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmptyHeading([NotNull] MarkdownParser.EmptyHeadingContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.atxHeading"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtxHeading([NotNull] MarkdownParser.AtxHeadingContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.atxHeading"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtxHeading([NotNull] MarkdownParser.AtxHeadingContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.headingStart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHeadingStart([NotNull] MarkdownParser.HeadingStartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.headingStart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHeadingStart([NotNull] MarkdownParser.HeadingStartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.horizontalLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHorizontalLine([NotNull] MarkdownParser.HorizontalLineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.horizontalLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHorizontalLine([NotNull] MarkdownParser.HorizontalLineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.hLineDBegin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHLineDBegin([NotNull] MarkdownParser.HLineDBeginContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.hLineDBegin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHLineDBegin([NotNull] MarkdownParser.HLineDBeginContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.hLineUBegin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHLineUBegin([NotNull] MarkdownParser.HLineUBeginContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.hLineUBegin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHLineUBegin([NotNull] MarkdownParser.HLineUBeginContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.hLineSBegin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHLineSBegin([NotNull] MarkdownParser.HLineSBeginContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.hLineSBegin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHLineSBegin([NotNull] MarkdownParser.HLineSBeginContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.indent3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndent3([NotNull] MarkdownParser.Indent3Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.indent3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndent3([NotNull] MarkdownParser.Indent3Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.indent2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndent2([NotNull] MarkdownParser.Indent2Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.indent2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndent2([NotNull] MarkdownParser.Indent2Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.indent1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndent1([NotNull] MarkdownParser.Indent1Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.indent1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndent1([NotNull] MarkdownParser.Indent1Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.fencedCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFencedCode([NotNull] MarkdownParser.FencedCodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.fencedCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFencedCode([NotNull] MarkdownParser.FencedCodeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.indentedCodeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndentedCodeBlock([NotNull] MarkdownParser.IndentedCodeBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.indentedCodeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndentedCodeBlock([NotNull] MarkdownParser.IndentedCodeBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.indentedCode1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndentedCode1([NotNull] MarkdownParser.IndentedCode1Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.indentedCode1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndentedCode1([NotNull] MarkdownParser.IndentedCode1Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList([NotNull] MarkdownParser.ListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList([NotNull] MarkdownParser.ListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.list1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList1([NotNull] MarkdownParser.List1Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.list1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList1([NotNull] MarkdownParser.List1Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.list2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList2([NotNull] MarkdownParser.List2Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.list2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList2([NotNull] MarkdownParser.List2Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.list3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList3([NotNull] MarkdownParser.List3Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.list3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList3([NotNull] MarkdownParser.List3Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.iList3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIList3([NotNull] MarkdownParser.IList3Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.iList3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIList3([NotNull] MarkdownParser.IList3Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.iList2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIList2([NotNull] MarkdownParser.IList2Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.iList2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIList2([NotNull] MarkdownParser.IList2Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.iList1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIList1([NotNull] MarkdownParser.IList1Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.iList1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIList1([NotNull] MarkdownParser.IList1Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.iList0"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIList0([NotNull] MarkdownParser.IList0Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.iList0"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIList0([NotNull] MarkdownParser.IList0Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.iListItem3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIListItem3([NotNull] MarkdownParser.IListItem3Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.iListItem3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIListItem3([NotNull] MarkdownParser.IListItem3Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.iListItem2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIListItem2([NotNull] MarkdownParser.IListItem2Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.iListItem2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIListItem2([NotNull] MarkdownParser.IListItem2Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.iListItem1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIListItem1([NotNull] MarkdownParser.IListItem1Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.iListItem1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIListItem1([NotNull] MarkdownParser.IListItem1Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.iListItem0"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIListItem0([NotNull] MarkdownParser.IListItem0Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.iListItem0"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIListItem0([NotNull] MarkdownParser.IListItem0Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.iListBegin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIListBegin([NotNull] MarkdownParser.IListBeginContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.iListBegin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIListBegin([NotNull] MarkdownParser.IListBeginContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.eList3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEList3([NotNull] MarkdownParser.EList3Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.eList3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEList3([NotNull] MarkdownParser.EList3Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.eList2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEList2([NotNull] MarkdownParser.EList2Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.eList2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEList2([NotNull] MarkdownParser.EList2Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.eList1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEList1([NotNull] MarkdownParser.EList1Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.eList1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEList1([NotNull] MarkdownParser.EList1Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.eList0"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEList0([NotNull] MarkdownParser.EList0Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.eList0"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEList0([NotNull] MarkdownParser.EList0Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.eListItem3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEListItem3([NotNull] MarkdownParser.EListItem3Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.eListItem3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEListItem3([NotNull] MarkdownParser.EListItem3Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.eListItem2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEListItem2([NotNull] MarkdownParser.EListItem2Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.eListItem2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEListItem2([NotNull] MarkdownParser.EListItem2Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.eListItem1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEListItem1([NotNull] MarkdownParser.EListItem1Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.eListItem1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEListItem1([NotNull] MarkdownParser.EListItem1Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.eListItem0"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEListItem0([NotNull] MarkdownParser.EListItem0Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.eListItem0"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEListItem0([NotNull] MarkdownParser.EListItem0Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.eListBegin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEListBegin([NotNull] MarkdownParser.EListBeginContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.eListBegin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEListBegin([NotNull] MarkdownParser.EListBeginContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.blockQuote"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlockQuote([NotNull] MarkdownParser.BlockQuoteContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.blockQuote"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlockQuote([NotNull] MarkdownParser.BlockQuoteContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.blockQuoteLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlockQuoteLine([NotNull] MarkdownParser.BlockQuoteLineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.blockQuoteLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlockQuoteLine([NotNull] MarkdownParser.BlockQuoteLineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.emptyBlockQuoteLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmptyBlockQuoteLine([NotNull] MarkdownParser.EmptyBlockQuoteLineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.emptyBlockQuoteLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmptyBlockQuoteLine([NotNull] MarkdownParser.EmptyBlockQuoteLineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.blockQuoteStart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlockQuoteStart([NotNull] MarkdownParser.BlockQuoteStartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.blockQuoteStart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlockQuoteStart([NotNull] MarkdownParser.BlockQuoteStartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTable([NotNull] MarkdownParser.TableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTable([NotNull] MarkdownParser.TableContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.headerRow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHeaderRow([NotNull] MarkdownParser.HeaderRowContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.headerRow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHeaderRow([NotNull] MarkdownParser.HeaderRowContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.contentRow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContentRow([NotNull] MarkdownParser.ContentRowContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.contentRow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContentRow([NotNull] MarkdownParser.ContentRowContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.cellContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCellContent([NotNull] MarkdownParser.CellContentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.cellContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCellContent([NotNull] MarkdownParser.CellContentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.separatorRow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSeparatorRow([NotNull] MarkdownParser.SeparatorRowContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.separatorRow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSeparatorRow([NotNull] MarkdownParser.SeparatorRowContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.separatorContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSeparatorContent([NotNull] MarkdownParser.SeparatorContentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.separatorContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSeparatorContent([NotNull] MarkdownParser.SeparatorContentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.imageLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImageLine([NotNull] MarkdownParser.ImageLineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.imageLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImageLine([NotNull] MarkdownParser.ImageLineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.textLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTextLine([NotNull] MarkdownParser.TextLineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.textLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTextLine([NotNull] MarkdownParser.TextLineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.requiredText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRequiredText([NotNull] MarkdownParser.RequiredTextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.requiredText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRequiredText([NotNull] MarkdownParser.RequiredTextContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.optionalText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOptionalText([NotNull] MarkdownParser.OptionalTextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.optionalText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOptionalText([NotNull] MarkdownParser.OptionalTextContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.displayText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDisplayText([NotNull] MarkdownParser.DisplayTextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.displayText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDisplayText([NotNull] MarkdownParser.DisplayTextContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.linkText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLinkText([NotNull] MarkdownParser.LinkTextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.linkText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLinkText([NotNull] MarkdownParser.LinkTextContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.urlText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUrlText([NotNull] MarkdownParser.UrlTextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.urlText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUrlText([NotNull] MarkdownParser.UrlTextContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.headingText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHeadingText([NotNull] MarkdownParser.HeadingTextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.headingText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHeadingText([NotNull] MarkdownParser.HeadingTextContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.link"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLink([NotNull] MarkdownParser.LinkContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.link"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLink([NotNull] MarkdownParser.LinkContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.urlLink"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUrlLink([NotNull] MarkdownParser.UrlLinkContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.urlLink"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUrlLink([NotNull] MarkdownParser.UrlLinkContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.textLink"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTextLink([NotNull] MarkdownParser.TextLinkContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.textLink"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTextLink([NotNull] MarkdownParser.TextLinkContext context);
}
} // namespace MarkdownParsing
