//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/artur/RiderProjects/Markdown-to-LaTeX/Markdown-to-LaTeX/Markdown.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace MarkdownParsing {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="Markdown"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IMarkdownVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.document"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDocument([NotNull] Markdown.DocumentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>atxHeading</c>
	/// labeled alternative in <see cref="Markdown.heading"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtxHeading([NotNull] Markdown.AtxHeadingContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>setextHeading</c>
	/// labeled alternative in <see cref="Markdown.heading"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSetextHeading([NotNull] Markdown.SetextHeadingContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>emptyHeading</c>
	/// labeled alternative in <see cref="Markdown.heading"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEmptyHeading([NotNull] Markdown.EmptyHeadingContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.headingStart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHeadingStart([NotNull] Markdown.HeadingStartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.setextEnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSetextEnd([NotNull] Markdown.SetextEndContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.horizontalLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHorizontalLine([NotNull] Markdown.HorizontalLineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.hLineDBegin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHLineDBegin([NotNull] Markdown.HLineDBeginContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.hLineUBegin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHLineUBegin([NotNull] Markdown.HLineUBeginContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.hLineSBegin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHLineSBegin([NotNull] Markdown.HLineSBeginContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.indent3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndent3([NotNull] Markdown.Indent3Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.indent2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndent2([NotNull] Markdown.Indent2Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.indent1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndent1([NotNull] Markdown.Indent1Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.fencedCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFencedCode([NotNull] Markdown.FencedCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.indentedCodeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndentedCodeBlock([NotNull] Markdown.IndentedCodeBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.indentedCode1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndentedCode1([NotNull] Markdown.IndentedCode1Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitList([NotNull] Markdown.ListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.list1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitList1([NotNull] Markdown.List1Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.list2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitList2([NotNull] Markdown.List2Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.list3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitList3([NotNull] Markdown.List3Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.iList3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIList3([NotNull] Markdown.IList3Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.iList2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIList2([NotNull] Markdown.IList2Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.iList1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIList1([NotNull] Markdown.IList1Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.iList0"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIList0([NotNull] Markdown.IList0Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.iListItem3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIListItem3([NotNull] Markdown.IListItem3Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.iListItem2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIListItem2([NotNull] Markdown.IListItem2Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.iListItem1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIListItem1([NotNull] Markdown.IListItem1Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.iListItem0"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIListItem0([NotNull] Markdown.IListItem0Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.iListBegin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIListBegin([NotNull] Markdown.IListBeginContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.eList3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEList3([NotNull] Markdown.EList3Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.eList2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEList2([NotNull] Markdown.EList2Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.eList1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEList1([NotNull] Markdown.EList1Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.eList0"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEList0([NotNull] Markdown.EList0Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.eListItem3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEListItem3([NotNull] Markdown.EListItem3Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.eListItem2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEListItem2([NotNull] Markdown.EListItem2Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.eListItem1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEListItem1([NotNull] Markdown.EListItem1Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.eListItem0"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEListItem0([NotNull] Markdown.EListItem0Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.eListBegin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEListBegin([NotNull] Markdown.EListBeginContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.blockQuote"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockQuote([NotNull] Markdown.BlockQuoteContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.blockQuoteLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockQuoteLine([NotNull] Markdown.BlockQuoteLineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.emptyBlockQuoteLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEmptyBlockQuoteLine([NotNull] Markdown.EmptyBlockQuoteLineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.blockQuoteStart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockQuoteStart([NotNull] Markdown.BlockQuoteStartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable([NotNull] Markdown.TableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.headerRow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHeaderRow([NotNull] Markdown.HeaderRowContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.contentRow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContentRow([NotNull] Markdown.ContentRowContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.cellContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCellContent([NotNull] Markdown.CellContentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.separatorRow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSeparatorRow([NotNull] Markdown.SeparatorRowContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.separatorContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSeparatorContent([NotNull] Markdown.SeparatorContentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.imageLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImageLine([NotNull] Markdown.ImageLineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.textLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTextLine([NotNull] Markdown.TextLineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.requiredText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRequiredText([NotNull] Markdown.RequiredTextContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.optionalText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptionalText([NotNull] Markdown.OptionalTextContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.displayText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDisplayText([NotNull] Markdown.DisplayTextContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.linkText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLinkText([NotNull] Markdown.LinkTextContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.urlText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUrlText([NotNull] Markdown.UrlTextContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.headingText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHeadingText([NotNull] Markdown.HeadingTextContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.fencedText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFencedText([NotNull] Markdown.FencedTextContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.link"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLink([NotNull] Markdown.LinkContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.urlLink"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUrlLink([NotNull] Markdown.UrlLinkContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Markdown.textLink"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTextLink([NotNull] Markdown.TextLinkContext context);
}
} // namespace MarkdownParsing
