//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/artur/RiderProjects/Markdown-to-LaTeX/Markdown-to-LaTeX/MarkdownParser.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace MarkdownParsing {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IMarkdownParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class MarkdownParserBaseListener : IMarkdownParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.document"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDocument([NotNull] MarkdownParser.DocumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.document"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDocument([NotNull] MarkdownParser.DocumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.heading"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHeading([NotNull] MarkdownParser.HeadingContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.heading"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHeading([NotNull] MarkdownParser.HeadingContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.emptyHeading"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEmptyHeading([NotNull] MarkdownParser.EmptyHeadingContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.emptyHeading"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEmptyHeading([NotNull] MarkdownParser.EmptyHeadingContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.atxHeading"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtxHeading([NotNull] MarkdownParser.AtxHeadingContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.atxHeading"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtxHeading([NotNull] MarkdownParser.AtxHeadingContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.headingStart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHeadingStart([NotNull] MarkdownParser.HeadingStartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.headingStart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHeadingStart([NotNull] MarkdownParser.HeadingStartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.horizontalLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHorizontalLine([NotNull] MarkdownParser.HorizontalLineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.horizontalLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHorizontalLine([NotNull] MarkdownParser.HorizontalLineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.hLineDBegin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHLineDBegin([NotNull] MarkdownParser.HLineDBeginContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.hLineDBegin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHLineDBegin([NotNull] MarkdownParser.HLineDBeginContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.hLineUBegin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHLineUBegin([NotNull] MarkdownParser.HLineUBeginContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.hLineUBegin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHLineUBegin([NotNull] MarkdownParser.HLineUBeginContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.hLineSBegin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHLineSBegin([NotNull] MarkdownParser.HLineSBeginContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.hLineSBegin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHLineSBegin([NotNull] MarkdownParser.HLineSBeginContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.indent3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndent3([NotNull] MarkdownParser.Indent3Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.indent3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndent3([NotNull] MarkdownParser.Indent3Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.indent2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndent2([NotNull] MarkdownParser.Indent2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.indent2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndent2([NotNull] MarkdownParser.Indent2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.indent1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndent1([NotNull] MarkdownParser.Indent1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.indent1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndent1([NotNull] MarkdownParser.Indent1Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.fencedCode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFencedCode([NotNull] MarkdownParser.FencedCodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.fencedCode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFencedCode([NotNull] MarkdownParser.FencedCodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.indentedCodeBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndentedCodeBlock([NotNull] MarkdownParser.IndentedCodeBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.indentedCodeBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndentedCodeBlock([NotNull] MarkdownParser.IndentedCodeBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.indentedCode1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndentedCode1([NotNull] MarkdownParser.IndentedCode1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.indentedCode1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndentedCode1([NotNull] MarkdownParser.IndentedCode1Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterList([NotNull] MarkdownParser.ListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitList([NotNull] MarkdownParser.ListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.list1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterList1([NotNull] MarkdownParser.List1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.list1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitList1([NotNull] MarkdownParser.List1Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.list2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterList2([NotNull] MarkdownParser.List2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.list2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitList2([NotNull] MarkdownParser.List2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.list3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterList3([NotNull] MarkdownParser.List3Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.list3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitList3([NotNull] MarkdownParser.List3Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.iList3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIList3([NotNull] MarkdownParser.IList3Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.iList3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIList3([NotNull] MarkdownParser.IList3Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.iList2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIList2([NotNull] MarkdownParser.IList2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.iList2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIList2([NotNull] MarkdownParser.IList2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.iList1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIList1([NotNull] MarkdownParser.IList1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.iList1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIList1([NotNull] MarkdownParser.IList1Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.iList0"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIList0([NotNull] MarkdownParser.IList0Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.iList0"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIList0([NotNull] MarkdownParser.IList0Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.iListItem3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIListItem3([NotNull] MarkdownParser.IListItem3Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.iListItem3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIListItem3([NotNull] MarkdownParser.IListItem3Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.iListItem2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIListItem2([NotNull] MarkdownParser.IListItem2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.iListItem2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIListItem2([NotNull] MarkdownParser.IListItem2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.iListItem1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIListItem1([NotNull] MarkdownParser.IListItem1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.iListItem1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIListItem1([NotNull] MarkdownParser.IListItem1Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.iListItem0"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIListItem0([NotNull] MarkdownParser.IListItem0Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.iListItem0"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIListItem0([NotNull] MarkdownParser.IListItem0Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.iListBegin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIListBegin([NotNull] MarkdownParser.IListBeginContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.iListBegin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIListBegin([NotNull] MarkdownParser.IListBeginContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.eList3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEList3([NotNull] MarkdownParser.EList3Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.eList3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEList3([NotNull] MarkdownParser.EList3Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.eList2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEList2([NotNull] MarkdownParser.EList2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.eList2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEList2([NotNull] MarkdownParser.EList2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.eList1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEList1([NotNull] MarkdownParser.EList1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.eList1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEList1([NotNull] MarkdownParser.EList1Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.eList0"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEList0([NotNull] MarkdownParser.EList0Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.eList0"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEList0([NotNull] MarkdownParser.EList0Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.eListItem3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEListItem3([NotNull] MarkdownParser.EListItem3Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.eListItem3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEListItem3([NotNull] MarkdownParser.EListItem3Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.eListItem2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEListItem2([NotNull] MarkdownParser.EListItem2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.eListItem2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEListItem2([NotNull] MarkdownParser.EListItem2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.eListItem1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEListItem1([NotNull] MarkdownParser.EListItem1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.eListItem1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEListItem1([NotNull] MarkdownParser.EListItem1Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.eListItem0"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEListItem0([NotNull] MarkdownParser.EListItem0Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.eListItem0"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEListItem0([NotNull] MarkdownParser.EListItem0Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.eListBegin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEListBegin([NotNull] MarkdownParser.EListBeginContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.eListBegin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEListBegin([NotNull] MarkdownParser.EListBeginContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.blockQuote"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlockQuote([NotNull] MarkdownParser.BlockQuoteContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.blockQuote"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlockQuote([NotNull] MarkdownParser.BlockQuoteContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.blockQuoteLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlockQuoteLine([NotNull] MarkdownParser.BlockQuoteLineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.blockQuoteLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlockQuoteLine([NotNull] MarkdownParser.BlockQuoteLineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.emptyBlockQuoteLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEmptyBlockQuoteLine([NotNull] MarkdownParser.EmptyBlockQuoteLineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.emptyBlockQuoteLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEmptyBlockQuoteLine([NotNull] MarkdownParser.EmptyBlockQuoteLineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.blockQuoteStart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlockQuoteStart([NotNull] MarkdownParser.BlockQuoteStartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.blockQuoteStart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlockQuoteStart([NotNull] MarkdownParser.BlockQuoteStartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTable([NotNull] MarkdownParser.TableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTable([NotNull] MarkdownParser.TableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.headerRow"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHeaderRow([NotNull] MarkdownParser.HeaderRowContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.headerRow"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHeaderRow([NotNull] MarkdownParser.HeaderRowContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.contentRow"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContentRow([NotNull] MarkdownParser.ContentRowContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.contentRow"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContentRow([NotNull] MarkdownParser.ContentRowContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.cellContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCellContent([NotNull] MarkdownParser.CellContentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.cellContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCellContent([NotNull] MarkdownParser.CellContentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.separatorRow"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSeparatorRow([NotNull] MarkdownParser.SeparatorRowContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.separatorRow"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSeparatorRow([NotNull] MarkdownParser.SeparatorRowContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.separatorContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSeparatorContent([NotNull] MarkdownParser.SeparatorContentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.separatorContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSeparatorContent([NotNull] MarkdownParser.SeparatorContentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.imageLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImageLine([NotNull] MarkdownParser.ImageLineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.imageLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImageLine([NotNull] MarkdownParser.ImageLineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.textLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTextLine([NotNull] MarkdownParser.TextLineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.textLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTextLine([NotNull] MarkdownParser.TextLineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.requiredText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRequiredText([NotNull] MarkdownParser.RequiredTextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.requiredText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRequiredText([NotNull] MarkdownParser.RequiredTextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.optionalText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOptionalText([NotNull] MarkdownParser.OptionalTextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.optionalText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOptionalText([NotNull] MarkdownParser.OptionalTextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.displayText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDisplayText([NotNull] MarkdownParser.DisplayTextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.displayText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDisplayText([NotNull] MarkdownParser.DisplayTextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.linkText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLinkText([NotNull] MarkdownParser.LinkTextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.linkText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLinkText([NotNull] MarkdownParser.LinkTextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.urlText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUrlText([NotNull] MarkdownParser.UrlTextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.urlText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUrlText([NotNull] MarkdownParser.UrlTextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.headingText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHeadingText([NotNull] MarkdownParser.HeadingTextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.headingText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHeadingText([NotNull] MarkdownParser.HeadingTextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.link"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLink([NotNull] MarkdownParser.LinkContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.link"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLink([NotNull] MarkdownParser.LinkContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.urlLink"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUrlLink([NotNull] MarkdownParser.UrlLinkContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.urlLink"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUrlLink([NotNull] MarkdownParser.UrlLinkContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkdownParser.textLink"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTextLink([NotNull] MarkdownParser.TextLinkContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkdownParser.textLink"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTextLink([NotNull] MarkdownParser.TextLinkContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace MarkdownParsing
